env:
  - NODEJS_VER=12.16.2

language: node_js
node_js: $NODEJS_VER
warnings_are_errors: true

jobs:
  include:
    - stage: Push-Requests
      if: ( branch = master || branch = staging || branch = dev ) AND type = push
      script:
        - echo "CI/CD Starting for $BRANCH"
        - jq ".homepage = \"$HOST_URL\"" package.json > package_updated.json && mv package_updated.json package.json
        - npm install --production
        - npm run build
        - npm install -g firebase-tools
        - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
        - firebase deploy --only hosting:$FIREBASE_HOSTING_ID --token $FIREBASE_TOKEN
      after_success:
        - echo "Deployed Successfully"
    - stage: Dev-PR
      if: branch = dev AND type = pull_request
      script:
        - echo "CI/CD Starting for Development Pull Request"
        - jq ".homepage = \"$HOST_URL_PR/$TRAVIS_PULL_REQUEST\"" package.json > package_updated.json && mv package_updated.json package.json
        - npm install --production
        - npm run build
        # - mkdir build/$TRAVIS_PULL_REQUEST
        # - git clone --depth=50 --branch=dev https://$GITHUB_PERSONAL_ACCESS_TOKEN:x-oauth-basic@github.com/INTECS-UoM/$PR_BUILD_REPO_NAME.git
        # - shopt -s dotglob
        # - rsync -a build/* $PR_BUILD_REPO_NAME/$TRAVIS_PULL_REQUEST/
        # - rm -rf build/*
        # - rsync -a $PR_BUILD_REPO_NAME/* build/
        # - cd build
        # - jq -n --arg TRAVIS_BUILD_ID $TRAVIS_BUILD_ID '{"TRAVIS_BUILD_ID":$TRAVIS_BUILD_ID}' > travis-$TRAVIS_PULL_REQUEST.json
        # - git add .
        # - git commit -m "Build for Pull $TRAVIS_PULL_REQUEST"
        # - git push
        # - cd ..
        # - npm install -g firebase-tools
        # - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
        # - firebase deploy --only hosting:$FIREBASE_PR_HOSTING_ID --token $FIREBASE_TOKEN
      after_success:
        - echo "CI Successfully"
